version: "3.9"

services:
  cryptotrack-db:
    image: postgres:15
    container_name: cryptotrack-db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cryptotrack
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
